name: linc
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - transformers
  - accelerate
  - datasets
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tqdm
  - nltk
  - pip
  - matplotlib
  - scikit-learn
  - pip:
      - guidance
      - ipykernel